<a href="https://colab.research.google.com/github/Z-e-e/Z-e-e/blob/master/ageb_indicators_fin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

import json
import pandas as pd
import numpy as np


pd.set_option('display.max_column', None)
pd.set_option('display.max_row', None)
pd.set_option('display.max_colwidth', -1)

import warnings

warnings.filterwarnings('ignore')

Mounted at /content/gdrive


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  # This is added back by InteractiveShellApp.init_path()


In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sqlalchemy import create_engine

In [ ]:
#TEST
#df = pd.read_csv('gdrive/My Drive/Tegger/inegi_csv/RESAGEBURB_01CSV20.csv')
#df3 = pd.read_csv('gdrive/My Drive/Tegger/inegi_csv/RESAGEBURB_02CSV20.csv')
#df4 = pd.read_csv('gdrive/My Drive/Tegger/inegi_csv/RESAGEBURB_03CSV20.csv')
#df5 = pd.read_csv('gdrive/My Drive/Tegger/inegi_csv/RESAGEBURB_04CSV20.csv')

#frames = [df,df3, df4, df5]

#df = pd.concat(frames)

#df.head()

In [ ]:
df = pd.DataFrame()

i = 1

while i<33:
  if i<10:
    PATH = 'gdrive/My Drive/Tegger/inegi_csv/RESAGEBURB_0' + str(i) + 'CSV20.csv'
    nm = str(i) + 'CSV20.csv'
    df1 = pd.read_csv(PATH)
    frames = [df1, df]
    df = pd.concat(frames)
    print('current', i)
    print(nm)
    i+=1
    print('next', i)
  elif i>=10:
    PATH = 'gdrive/My Drive/Tegger/inegi_csv/RESAGEBURB_' + str(i) + 'CSV20.csv'
    nm = str(i) + 'CSV20.csv'
    df1 = pd.read_csv(PATH)
    frames = [df1, df]
    df = pd.concat(frames)
    print('current', i)
    print(nm)
    i+=1
    print('next', i)

current 1
1CSV20.csv
next 2
current 2
2CSV20.csv
next 3
current 3
3CSV20.csv
next 4
current 4
4CSV20.csv
next 5
current 5
5CSV20.csv
next 6
current 6
6CSV20.csv
next 7
current 7
7CSV20.csv
next 8
current 8
8CSV20.csv
next 9
current 9
9CSV20.csv
next 10
current 10
10CSV20.csv
next 11
current 11
11CSV20.csv
next 12
current 12
12CSV20.csv
next 13
current 13
13CSV20.csv
next 14
current 14
14CSV20.csv
next 15
current 15
15CSV20.csv
next 16
current 16
16CSV20.csv
next 17
current 17
17CSV20.csv
next 18
current 18
18CSV20.csv
next 19
current 19
19CSV20.csv
next 20
current 20
20CSV20.csv
next 21
current 21
21CSV20.csv
next 22
current 22
22CSV20.csv
next 23
current 23
23CSV20.csv
next 24
current 24
24CSV20.csv
next 25
current 25
25CSV20.csv
next 26
current 26
26CSV20.csv
next 27
current 27
27CSV20.csv
next 28
current 28
28CSV20.csv
next 29
current 29
29CSV20.csv
next 30
current 30
30CSV20.csv
next 31
current 31
31CSV20.csv
next 32
current 32
32CSV20.csv
next 33


In [ ]:
tot = len(df)
tot

1489061

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1489061 entries, 0 to 14898
Columns: 229 entries, ENTIDAD to VPH_SINTIC
dtypes: int64(6), object(223)
memory usage: 2.6+ GB


In [ ]:
len(df.columns)

229

In [ ]:
df.describe()

ENTIDAD           MUN           LOC           MZA        POBTOT  \
count  1.489061e+06  1.489061e+06  1.489061e+06  1.489061e+06  1.489061e+06   
mean   1.674082e+01  4.856216e+01  2.251619e+01  2.561759e+01  3.687689e+02   
std    8.366015e+00  6.358198e+01  9.876513e+01  5.589805e+01  2.507395e+04   
min    1.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
25%    1.000000e+01  1.100000e+01  1.000000e+00  7.000000e+00  2.200000e+01   
50%    1.500000e+01  3.000000e+01  1.000000e+00  1.800000e+01  4.900000e+01   
75%    2.400000e+01  6.000000e+01  1.000000e+00  3.200000e+01  9.500000e+01   
max    3.200000e+01  5.700000e+02  2.371000e+03  8.000000e+02  1.699242e+07   

             VIVTOT  
count  1.489061e+06  
mean   1.277515e+02  
std    8.494052e+03  
min    0.000000e+00  
25%    8.000000e+00  
50%    1.800000e+01  
75%    3.200000e+01  
max    5.403492e+06

In [ ]:
df = df.sort_values(by=['NOM_ENT'])

In [ ]:
df.head()

ENTIDAD         NOM_ENT  MUN                    NOM_MUN  LOC  \
14898  1        Aguascalientes  11   San Francisco de los Romo  138   
4971   1        Aguascalientes  1    Aguascalientes             1     
4970   1        Aguascalientes  1    Aguascalientes             1     
4969   1        Aguascalientes  1    Aguascalientes             1     
4968   1        Aguascalientes  1    Aguascalientes             1     

                           NOM_LOC  AGEB  MZA  POBTOT POBFEM POBMAS P_0A2  \
14898  La Ribera [Fraccionamiento]  023A  44   164     79     85     9      
4971   Aguascalientes               2634  2    103     54     49     3      
4970   Aguascalientes               2634  1    37      *      *      *      
4969   Total AGEB urbana            2634  0    3325    1707   1618   152    
4968   Aguascalientes               262A  33   164     87     77     6      

      P_0A2_F P_0A2_M P_3YMAS P_3YMAS_F P_3YMAS_M P_5YMAS P_5YMAS_F P_5YMAS_M  \
14898  5       4       155     74        81        144     66        78         
4971   *       *       96      51        45        94      49        45         
4970   *       *       *       *         *         *       *         *          
4969   71      81      3169    1634      1535      3060    1580      1480       
4968   5       *       158     82        76        153     78        75         

      P_12YMAS P_12YMAS_F P_12YMAS_M P_15YMAS P_15YMAS_F P_15YMAS_M P_18YMAS  \
14898  112      52         60         108      50         58         98        
4971   85       43         42         77       37         40         64        
4970   *        *          *          *        *          *          *         
4969   2636     1377       1259       2464     1290       1174       2265      
4968   134      65         69         128      63         65         120       

      P_18YMAS_F P_18YMAS_M P_3A5 P_3A5_F P_3A5_M P_6A11 P_6A11_F P_6A11_M  \
14898  44         54         15    8       7       28     14       14        
4971   30         34         3     3       0       8      5        3         
4970   *          *          *     *       *       *      *        *         
4969   1186       1079       168   73      95      365    184      181       
4968   59         61         8     7       *       16     10       6         

      P_8A14 P_8A14_F P_8A14_M P_12A14 P_12A14_F P_12A14_M P_15A17 P_15A17_F  \
14898  21     9        12       4       *         *         10      6          
4971   11     8        3        8       6         *         13      7          
4970   *      *        *        *       *         *         *       *          
4969   395    205      190      172     87        85        199     104        
4968   15     8        7        6       *         4         8       4          

      P_15A17_M P_18A24 P_18A24_F P_18A24_M P_15A49_F P_60YMAS P_60YMAS_F  \
14898  4         25      8         17        44        3        *           
4971   6         14      6         8         31        5        *           
4970   *         *       *         *         *         *        *           
4969   95        475     239       236       929       241      126         
4968   4         28      10        18        46        9        5           

      P_60YMAS_M REL_H_M POB0_14 POB15_64 POB65_MAS PROM_HNV PNACENT  \
14898  *          107.59  56      107      *         2.06     127      
4971   3          90.74   22      74       3         1.84     76       
4970   *          *       *       *        *         *        *        
4969   115        94.79   857     2319     145       2.09     2581     
4968   4          88.51   36      122      6         2.22     133      

      PNACENT_F PNACENT_M PNACOE PNACOE_F PNACOE_M PRES2015 PRES2015_F  \
14898  67        60        37     12       25       116      57          
4971   41        35        20     9        11       87       46          
4970   *         *         *      *        *        *        *           
4969   

In [ ]:
#Clave que identifica a la manzana, al inter�or de una AGEB, de acuerdo a la desagregaci�n del Marco Geoestad�stico.

In [ ]:
#df1 reduced df
columns = ['ENTIDAD', 'MUN', 'LOC', 'AGEB', 'MZA','VPH_REFRI', 'VPH_LAVAD','VPH_TV', 'VPH_PC','GRAPROES', 'P18YM_PB', 'P_18YMAS']

df1 = pd.DataFrame()

for col in columns:
  df1[col] = df[col]


df1.head()

#df2 copy
df2 = df1.copy()

#new df2
df2['AGEB_Key']=df.apply(lambda x:'%s%s%s%s' % (x['ENTIDAD'],x['MUN'],x['LOC'],x['AGEB']),axis=1)
df2.head()

#ageb1 copy
ageb1 = df2.copy()
#obj to num
columns = ['VPH_REFRI', 'VPH_LAVAD','VPH_TV', 'VPH_PC','GRAPROES', 'P18YM_PB', 'P_18YMAS']

for col in columns:
  ageb1[col] = pd.to_numeric(ageb1[col], errors = 'coerce')

ageb1.head()

#pop with refrigirators, washers, TVs and PCs
ageb1['pop_4_products'] = ageb1['VPH_REFRI'] + ageb1['VPH_LAVAD'] + ageb1['VPH_TV'] + ageb1['VPH_PC'] #double counting posible

ageb1['compu'] = ageb1['VPH_PC'] / ageb1['pop_4_products']

#average level of education (132)
ageb1['esc'] = ageb1['GRAPROES']/ageb1['GRAPROES'].max()

#population aged 18+ w/ post-basic education / population of people 18 yo and older
ageb1['edusup'] = ageb1['P18YM_PB'] / ageb1['P_18YMAS']

ageb1.head()

ENTIDAD  MUN  LOC  AGEB  MZA  VPH_REFRI  VPH_LAVAD  VPH_TV  VPH_PC  \
14898  1        11   138  023A  44   43.0       34.0       42.0    4.0      
4971   1        1    1    2634  2    24.0       19.0       24.0    12.0     
4970   1        1    1    2634  1   NaN        NaN        NaN     NaN       
4969   1        1    1    2634  0    794.0      720.0      814.0   332.0    
4968   1        1    1    262A  33   40.0       38.0       40.0    18.0     

       GRAPROES  P18YM_PB  P_18YMAS    AGEB_Key  pop_4_products     compu  \
14898  8.57      23.0      98.0      111138023A  123.0           0.032520   
4971   9.65      27.0      64.0      1112634     79.0            0.151899   
4970  NaN       NaN       NaN        1112634    NaN             NaN         
4969   9.66      970.0     2265.0    1112634     2660.0          0.124812   
4968   9.64      51.0      120.0     111262A     136.0           0.132353   

            esc    edusup  
14898  0.375877  0.234694  
4971   0.423246  0.421875  
4970  NaN       NaN        
4969   0.423684  0.428256  
4968   0.422807  0.425000

In [ ]:
imp_cols = ['compu','esc', 'edusup']
ageb1 = ageb1.dropna(subset = imp_cols)

ind_trial = ageb1.iloc[:, -3:]
ind_trial.head()

print(ind_trial.corr())

#PCA
indicators = ['compu', 'esc', 'edusup' ]
x = ageb1.loc[:, indicators].values

x = StandardScaler().fit_transform(x)

print(np.mean(x),np.std(x))

print(x[:5])

print(range(x.shape[1]))

print(x.shape[1])

print(x[:5,0])

ind_cols = ['comp', 'esc', 'edusup' ]
#for i in range(x.shape[1]):
#  'indicators'+str(i)
norm_ind = pd.DataFrame(x,columns=ind_cols)
norm_ind.head()


inds = ageb1.iloc[:, -3:]
#inds.head()
print(norm_ind.corr())

pca_ind = PCA(n_components=3)
pc_ind = pca_ind.fit_transform(x)

print(pc_ind)

pc_df = pd.DataFrame(data = pc_ind
             , columns = ['pc_1', 'pc_2', 'pc_3'])

print(pc_df.head())

print("pc_df length".format(len(pc_df)))

print('variance explained per component: {}'.format(pca_ind.explained_variance_ratio_))


ageb_1 = ageb1.reset_index()
print(ageb_1.head())

pca_ageb = pd.merge(ageb_1, pc_df, left_index = True, right_index = True)
print(pca_ageb.head())

pca_ageb['rating'] = np.where(pca_ageb['pc_1']<=-0.4, 'E', 
                              (np.where(pca_ageb['pc_1']<=0.05, 'D',
                                        (np.where(pca_ageb['pc_1']<=0.34, 'D+',
                                                   (np.where(pca_ageb['pc_1']<=0.68, 'C-',
                                                              (np.where(pca_ageb['pc_1']<=1.25, 'C',
                                                                         (np.where(pca_ageb['pc_1']<=2.41, 'C+',
                                                                                    (np.where(pca_ageb['pc_1']>2.41, 'A/B',0)))))))))))))


pca_ageb1 = pca_ageb.copy()
pca_ageb1.head()

           compu       esc    edusup
compu   1.000000  0.787130  0.777215
esc     0.787130  1.000000  0.956261
edusup  0.777215  0.956261  1.000000
1.0917303829431791e-16 0.9999999999999994
[[-1.78740012 -0.94075236 -1.37088514]
 [ 0.16539385 -0.44963924 -0.53007509]
 [-0.2776909  -0.4450919  -0.50141158]
 [-0.15433655 -0.45418659 -0.51603772]
 [ 0.31902161  0.80997495  0.45860662]]
range(0, 3)
3
[-1.78740012  0.16539385 -0.2776909  -0.15433655  0.31902161]
            comp       esc    edusup
comp    1.000000  0.787130  0.777215
esc     0.787130  1.000000  0.956261
edusup  0.777215  0.956261  1.000000
[[ 2.34719309 -0.58796125 -0.32268626]
 [ 0.4880177   0.51998427 -0.04433121]
 [ 0.71175942  0.13650306 -0.03739048]
 ...
 [ 0.34572717  0.96021685 -0.4782519 ]
 [ 1.51329183  0.19067447 -0.53123506]
 [ 1.18384076  0.04709316 -0.121073  ]]
       pc_1      pc_2      pc_3
0  2.347193 -0.587961 -0.322686
1  0.488018  0.519984 -0.044331
2  0.711759  0.136503 -0.037390
3  0.658025  0.248862 

index  ENTIDAD  MUN  LOC  AGEB  MZA  VPH_REFRI  VPH_LAVAD  VPH_TV  VPH_PC  \
0  14898  1        11   138  023A  44   43.0       34.0       42.0    4.0      
1  4971   1        1    1    2634  2    24.0       19.0       24.0    12.0     
2  4969   1        1    1    2634  0    794.0      720.0      814.0   332.0    
3  4968   1        1    1    262A  33   40.0       38.0       40.0    18.0     
4  4967   1        1    1    262A  31   35.0       35.0       34.0    20.0     

   GRAPROES  P18YM_PB  P_18YMAS    AGEB_Key  pop_4_products     compu  \
0  8.57      23.0      98.0      111138023A  123.0           0.032520   
1  9.65      27.0      64.0      1112634     79.0            0.151899   
2  9.66      970.0     2265.0    1112634     2660.0          0.124812   
3  9.64      51.0      120.0     111262A     136.0           0.132353   
4  12.42     52.0      81.0      111262A     124.0           0.161290   

        esc    edusup      pc_1      pc_2      pc_3 rating  
0  0.375877  0.234694  2.347193 -0.587961 -0.322686  C+     
1  0.423246  0.421875  0.488018  0.519984 -0.044331  C-     
2  0.423684  0.428256  0.711759  0.136503 -0.037390  C      
3  0.422807  0.425000  0.658025  0.248862 -0.038356  C-     
4  0.544737  0.641975 -0.925202 -0.219661 -0.252794  E

In [ ]:
pca_ageb1.head()

index  ENTIDAD  MUN  LOC  AGEB  MZA  VPH_REFRI  VPH_LAVAD  VPH_TV  VPH_PC  \
0  14898  1        11   138  023A  44   43.0       34.0       42.0    4.0      
1  4971   1        1    1    2634  2    24.0       19.0       24.0    12.0     
2  4969   1        1    1    2634  0    794.0      720.0      814.0   332.0    
3  4968   1        1    1    262A  33   40.0       38.0       40.0    18.0     
4  4967   1        1    1    262A  31   35.0       35.0       34.0    20.0     

   GRAPROES  P18YM_PB  P_18YMAS    AGEB_Key  pop_4_products     compu  \
0  8.57      23.0      98.0      111138023A  123.0           0.032520   
1  9.65      27.0      64.0      1112634     79.0            0.151899   
2  9.66      970.0     2265.0    1112634     2660.0          0.124812   
3  9.64      51.0      120.0     111262A     136.0           0.132353   
4  12.42     52.0      81.0      111262A     124.0           0.161290   

        esc    edusup      pc_1      pc_2      pc_3 rating  
0  0.375877  0.234694  2.347193 -0.587961 -0.322686  C+     
1  0.423246  0.421875  0.488018  0.519984 -0.044331  C-     
2  0.423684  0.428256  0.711759  0.136503 -0.037390  C      
3  0.422807  0.425000  0.658025  0.248862 -0.038356  C-     
4  0.544737  0.641975 -0.925202 -0.219661 -0.252794  E

In [ ]:
#pca_ageb1.loc[pca_ageb1['AGEB'] == '2634'] #not sure what to do with these duplicates 140730001023A
pca_ageb1.loc[pca_ageb1['AGEB'] =='023A'] #14073 0001 023A #1473  #0001   #023A
#pca_ageb1.loc[pca_ageb1['AGEB'] =='017A'] #060100001017A  #

index  ENTIDAD  MUN  LOC  AGEB  MZA  VPH_REFRI  VPH_LAVAD  VPH_TV  \
0        14898   1        11   138  023A  44   43.0       34.0       42.0     
4579     14897   1        11   138  023A  43   47.0       40.0       48.0     
8600     14867   1        11   138  023A  13   26.0       25.0       29.0     
8601     14866   1        11   138  023A  12   16.0       12.0       21.0     
8602     14865   1        11   138  023A  11   30.0       26.0       35.0     
8603     14864   1        11   138  023A  10   35.0       30.0       37.0     
8604     14863   1        11   138  023A  9    27.0       21.0       30.0     
8605     14862   1        11   138  023A  8    10.0       3.0        7.0      
8606     14861   1        11   138  023A  7    21.0       17.0       20.0     
8607     14860   1        11   138  023A  6    39.0       28.0       51.0     
8608     14859   1        11   138  023A  5    33.0       21.0       40.0     
8609     14858   1        11   138  023A  4    27.0       21.0       27.0     
8610     14857   1        11   138  023A  3    28.0       21.0       28.0     
8611     14856   1        11   138  023A  2    42.0       28.0       51.0     
8612     14855   1        11   138  023A  1    40.0       34.0       44.0     
8613     14854   1        11   138  023A  0    1426.0     1130.0     1547.0   
8623     14869   1        11   138  023A  15   30.0       26.0       31.0     
8625     14872   1        11   138  023A  18   44.0       34.0       47.0     
8627     14896   1        11   138  023A  42   44.0       33.0       45.0     
8628     14894   1        11   138  023A  40   42.0       33.0       46.0     
8629     14893   1        11   138  023A  39   28.0       15.0       28.0     
8630     14892   1        11   138  023A  38   34.0       17.0       31.0     
8631     14891   1        11   138  023A  37   39.0       31.0       36.0     
8632     14890   1        11   138  023A  36   65.0       55.0       72.0     
8633     14889   1        11   138  023A  35   52.0       44.0       62.0     
8634     14888   1        11   138  023A  34   52.0       42.0       52.0     
8635     14886   1        11   138  023A  32   38.0       32.0       39.0     
8636     14885   1        11   138  023A  31   41.0       36.0       41.0     
8637     14884   1        11   138  023A  30   28.0       25.0       34.0     
8638     14883   1        11   138  023A  29   34.0       32.0       38.0     
8639     14882   1        11   138  023A  28   28.0       23.0       33.0     
8640     14881   1        11   138  023A  27   34.0       32.0       34.0     
8641     14880   1        11   138  023A  26   36.0       27.0       39.0     
8642     14878   1        11   138  023A  24   14.0       14.0       17.0     
8643     14877   1        11   138  023A  23   35.0       29.0       47.0     
8644     14876   1        11   138  023A  22   28.0       24.0       33.0     
8645     14875   1        11   138  023A  21   23.0       17.0       26.0     
8646     14873   1        11   138  023A  19   32.0       28.0       33.0     
8647     14871   1        11   138  023A  17   21.0       15.0       22.0     
9049     13119   1        6    1    023A  37   21.0       20.0       23.0     
9050     13117   1        6    1    023A  35   13.0       10.0       13.0     
9051     13116   1        6    1    023A  34   22.0       22.0       22.0     
9052     13115   1        6    1    023A  33   27.0       25.0       28.0     
9053     13114   1        6    1    023A  32   19.0       18.0       20.0     
9054     13113   1        6    1    023A  31   20.0       20.0       20.0     
9055     13112   1        6    1    023A  30   32.0       31.0       30.0     
9056     13111   1        6    1    023A  29   11.0       11.0       10.0     
9057     13110   1        6    1    023A  28   15.0       12.0       16.0     
9058     13109   1        6    1    023A  27   21.0       20.0       20.0     
9059     13108   1        6    1    023A  26   18.0       19

In [ ]:
fin_tab = pd.DataFrame()

columns = ['index','AGEB_Key', 'rating']

for col in columns:
  fin_tab[col] = pca_ageb1[col]

fin_tab.head()

index    AGEB_Key rating
0  14898  111138023A  C+   
1  4971   1112634     C-   
2  4969   1112634     C    
3  4968   111262A     C-   
4  4967   111262A     E

In [ ]:
tot = len(fin_tab)
tot

1019130

In [ ]:
piv = fin_tab.groupby('rating', as_index=False)[['AGEB_Key']].count()
piv = piv.rename(columns = {'AGEB_Key': 'AGEB_Count'})
piv = piv.rename(columns = {'rating': 'Rating'})
piv = piv.reindex([0,2,1,3,5,4,6])
piv['%'] = (piv['AGEB_Count'] / tot) * 100
piv['%'] = piv['%'].apply(lambda x: round(x, 2))

piv

rating  AGEB_Count      %
0  A/B    57911       5.68 
2  C+     180687      17.73
1  C      141324      13.87
3  C-     85623       8.40 
5  D+     70215       6.89 
4  D      98624       9.68 
6  E      384746      37.75

In [ ]:
fin_tab.to_csv(r'gdrive/My Drive/Tegger/ageb_rating_fin2.csv')

In [ ]:
test = fin_tab[:300000]

test.to_csv(r'gdrive/My Drive/Tegger/test2.csv')

In [ ]:
tst = fin_tab.copy()

In [ ]:
len(tst['AGEB_Key'][tst['AGEB_Key'].duplicated(keep=False)])

1010254

In [ ]:
len(fin_tab) - len(tst['AGEB_Key'][tst['AGEB_Key'].duplicated(keep=False)])

8876

In [ ]:
sp = pd.read_csv('gdrive/My Drive/Tegger/bq-results-20210308-124809-qh7g8dmi4rso.csv')

In [ ]:
sp.head(20)

AGEB_key
0   150990438    
1   240490064    
2   0600500010108
3   060020001091A
4   0601000010108
5   0601000010362
6   060040064    
7   060100001017A
8   0601000010432
9   0600200010708
10  0600900010272
11  0600900110380
12  0601000010574
13  0600200011068
14  0601000011318
15  2006700011448
16  204410021    
17  2007900010718
18  2006700010897
19  2006700011359

In [ ]:
len(sp)

999

In [ ]:
r = pd.read_csv('gdrive/My Drive/Tegger/new.csv')

In [ ]:
r.head()

AGEB_key
0  1112634
1  111262A
2  1112600
3  1112649
4  1112668

In [ ]:
len(r)

58759

In [ ]:
ageb_ex = sp['AGEB_key'].isin(r['AGEB_key'])
ageb_ex 

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     True 
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False

In [ ]:
new_indices = np.where(ageb_ex  == True)

In [ ]:
new_indices[0][0]

16

In [ ]:
print("{} ageb key available.".format(len(new_indices)))

1 ageb key available.


In [ ]:
#new_indices
in_both = sp.loc[16]
in_both 

AGEB_key
16  204410021

In [ ]:
f = sp['AGEB_key'].str.contains(r'023A', na=True)
new_indices = np.where(f == True)
new_indices[0][0]	

327

In [ ]:
in_both = sp.loc[327]
in_both 

AGEB_key    140730001023A
Name: 327, dtype: object

In [ ]:
#140730001023A #14       73   #0001   #023A
              #ENTIDAD, MUN           #AGEB
sp

AGEB_key
0    150990438    
1    240490064    
2    0600500010108
3    060020001091A
4    0601000010108
5    0601000010362
6    060040064    
7    060100001017A
8    0601000010432
9    0600200010708
10   0600900010272
11   0600900110380
12   0601000010574
13   0600200011068
14   0601000011318
15   2006700011448
16   204410021    
17   2007900010718
18   2006700010897
19   2006700011359
20   204270018    
21   2003900010695
22   203970055    
23   2005900010293
24   2006700512075
25   200670295    
26   2038500010270
27   2039100010028
28   2006700010331
29   2038500010247
30   200790116    
31   2039000030213
32   200910017    
33   2033800010088
34   203340163    
35   200730057    
36   2003900010568
37   200390055    
38   201430034    
39   205510038    
40   2004300010359
41   201840130    
42   200460026    
43   200670308    
44   2055100010112
45   204030016    
46   2004500010029
47   2006700012268
48   2013100010067
49   2001400010249
50   205150101    
51   2051500010690
52   2007900010506
53   2037500010077
54   2039000010143
55   2048200010236
56   2001400010037
57   2006700012272
58   204390042    
59   201840126    
60   203100001002A
61   2022700010055
62   200670312    
63   2010700010095
64   204820081    
65   200100042    
66   2111400013737
67   2111400012461
68   2111400013629
69   210410166    
70   2101000010028
71   2111400013351
72   2101900010451
73   2111400011425
74   2119700010294
75   2114400010055
76   2111400010821
77   2120800010143
78   2111400010361
79   2114000010501
80   211140001378A
81   2104100010255
82   2111400016642
83   2111400015004
84   2111400014824
85   2111400014006
86   2111400013953
87   2119700290237
88   2107100090413
89   2101900010606
90   2111400011177
91   2111400011406
92   2101900010428
93   2111400013099
94   212090032    
95   2111400013741
96   2111400013949
97   2116900010073
98   2117400010105
99   210760053    
100  2104500010201
101  2111400011641
102  2114200010188
103  2111400012476
104  2114000140291
105  2111400014129
106  2115400010263
107  2115600011139
108  21156022A    
109  2104100010240
110  2115600010605
111  2111400013671
112  2101500310344
113  2104700010210
114  2111900130508
115  2113200090158
116  2111400014773
117  2101900010413
118  210740097    
119  2111400015555
120  210190752    
121  2111400013370
122  2112200010058
123  2101900010678
124  2111500010119
125  211141088    
126  2108500010226
127  2104100040325
128  2111400013614
129  2111900010207
130  2111400010338
131  2111400016341
132  2114000010499
133  2111400013898
134  211560234    
135  211141073    
136  211140001086A
137  211140001321A
138  210440001005A
139  2118600010178
140  211740073    
141  2114900010102
142  2117200010064
143  2101500010217
144  211690020    
145  2111400013544
146  2111400013703
147  2111400016021
148  2115600010910
149  2115600011302
150  210850001025A
151  2111400012669
152  2109000010118
153  2111400015220
154  2111400013972
155  211140001442A
156  2111000110521
157  210100047    
158  2111400015199
159  2111400010130
160  211530016    
161  210530082    
162  2107100010038
163  2105300010275
164  260181756    
165  260304191    
166  260120237    
167  26018160A    
168  260330383    
169  260304350    
170  260420908    
171  260304187    
172  2603000015857
173  2601800010654
174  260300001191A
175  260304219    
176  260303812    
177  260303795    
178  260304083    
179  260304331    
180  260304469    
181  260291872    
182  260360328    
183  2604200010611
184  26042097A    
185  2603000012617
186  260304115    
187  260481702    
188  2604200010626
189  260430638    
190  260190505    
191  2604300010286
192  2604300010479
193  260291745    
194  2602900011088
195  260303916    
196  2602900012048
197  260291904    
198  26030387A    
199  260551463    
200  260551266    
201  260220286    
202  2603000013371
203  26017198A    
204  2604300012598
205  260304098    
206  070200109    
207  070890244    
208  071080152    
209  070890001094A
2